### ISSUE TITLE
Spring Boot Unit Test Example with embedded Cassandra DB?

### ISSUE THREAD

**Issue by Toomy** [nosan/embedded-cassandra-spring-boot#1]
Good Morning Nosan
I just stumbled over your project while searching for an easy way to create an SpringBoot Repository test with and embedded Cassandra under Junit 5.
Is it possible that you create an example how tho write such a text using your project and document it in the readme?

That would be awsome!

Thank you
Warkus

**Comment by nosan** [comment]
Hi @Toomy ,
Sorry for the long delay, I was a bit busy. I will create a small example tomorrow.

**Comment by nosan** [comment]
Here is a sample:
https://github.com/nosan/embedded-cassandra-spring-boot-sample

I would recommend use https://github.com/nosan/cassandra-test-spring-boot 

The latest was created with a focus on testing.

**Comment by Toomy** [comment]
Thank you nosan

**Comment by guidomaiola** [comment]
hi @nosan sorry for this late request .. your repo is very helpful. but i can see the examples is there any way to reopen or publish  if still there? i would appreciate so much. thanks !!

**Comment by nosan** [comment]
@guidomaiola Unfortunately, I've already removed all sample repositories.
